### ISSUE TITLE
recent changes break Pkg in even slightly older pups

### ISSUE THREAD

**Issue by sc0ttj** [puppylinux-woof-CE/Pkg#1]
Change here: https://github.com/puppylinux-woof-CE/Pkg/commit/6dc32299c45620e36d439c53c724bf2a6c2381a7

Is there a way to make this fix work on older Pups which don't have the `0setup` updates here https://github.com/puppylinux-woof-CE/woof-CE/commit/f99cf474e18c0881dc5b6512e271716d6333cbd0?

**Comment by wdlkmpx** [comment]
I added that commit because I realized that pkg was waiting forever for something... waiting for 0setup to finish. And it's not obvious that you must hit enter twice.

There is another way to fix it, and it also involves patching 0setup.

That commit is a result of my tests, I don't remember the command, repo-update or something.

It's easy for me to produce 6 isos.. all the slackos, but currently my upload speed is a bit slow.

**Comment by sc0ttj** [comment]
So we don't break backwards compatibilty, I propose this, at top of script:

```
# 0setup must be used differently in older and newer Woof-CE versions, so 
# check which version of 0setup we're using, then set a flag on how to use it
PKG_REPO_UPDATE_METHOD=${PKG_REPO_UPDATE_METHOD:-standard}
if [ "$(grep -m1 'if [ "$SETUPCALLEDFROM" = "ppm" ];then' /usr/local/petget/0setup)" = "" ];then
  PKG_REPO_UPDATE_METHOD=legacy
fi
export PKG_REPO_UPDATE_METHOD
```

Then later, when we call 0setup:

```
# if using the newer version of 0setup (with no popup dialogs)
if [ "$PKG_REPO_UPDATE_METHOD" = standard ];then
  0setup notppm ... # new one
# else, if we're using an older version  of 0setup
else
  DISPLAY='' blah 0setup # old one
fi
```

And so this way PKG_REPO_UPDATE_METHOD can be an ENV var, or defined in the `~/.pkg/pkgrc` file

**Comment by sc0ttj** [comment]
Even simpler, revert to the old line, but do this:

```
DISPLAY='' SETUPCALLEDFROM=ppm /usr/local/petget/0setup notppm &>$TMPDIR/update_repo_results
```

That should work for both new and old versions of 0setup, right? (Not sure)

**Comment by sc0ttj** [comment]
backwards compatibility added in a recent commit, closing this issue.
