### ISSUE TITLE
buildpet should be a plugin

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/Pkg#27]
The scripts in buildpet are ancient (very old versions, `yad-14.2` for example, plus no `arm` support) and probably have had zero testing recently.

Perhaps we need a new build-system for pet packages that takes the best of both `buildpet` and `petbuild` and merges into a streamline package build system.

My suggestion would be to remove it and add plugin support.

**Comment by sc0ttj** [comment]
How do you mean add "remove it and add plugin support"?
Can you flesh out what you mean please...

---

BTW, I do envisage doing a plugin system for Pkg, but a "petbuild" like system would be too complex to be created as a plugin for it..  Unless I come up with something I've not yet considered..

---

### New "ports-like" build system 

I agree we should take the best bits of both `buildpet` and `petbuild`... 

In terms of being able to compile stuff, I'm not sure what `buildpet` is missing that `petbuild` has - as far as I know, the only downside with buildpet is that it has old build scripts.. Please correct me here if I'm wrong..

Cos I'd prefer to port any features petbuild has (that we wanna keep) into buildpet, where needed, then update the buildpet build scripts (rather than kill buildpet and switch to petbuild)..  

---

## About build scripts

TBH, we keep hitting the same problem - not enough build scripts, and not enough people keeping them up to date ... 

Personally I think we should try to "go big" - I'd like to create a system which allows us to import build scripts from SboPkg, CRUX, Arch PKGBUILD, Venom Linux, Pkgsrc (etc) and convert them to something that can be run in Puppy (by buildpet/petbuild/newthing).. 

Not sure what others think about this.

If we roll our own, I think separate converter scripts like `sbo2petbuild` and `pkgbuild2petbuild` would be the best way to achieve this ... Living alongside the main 'petbuild' thing as helper scripts.

However, `src2pkg` can automate the generation/creation of build scripts - any successful build (from URL or archive file) can generate a working build script! :)

**Comment by sc0ttj** [comment]
I've also been having another look at `src2pkg`.

Just like `petbuild` and `buildpet`, it is also a nice candidate for a "nearly ready-made" ports-like solution.

It would be perfectly reasonable to extend its "slackBuild script to src2pkg build script" functionality, so that it could convert other formats to src2pkg build scripts (such as Arch PKGBUILD scripts, or whatever).

A good reason for using `src2pkg` as the basis for a new petbuild-esque thing would be that `src2pkg` can build packages reliably from its own build scripts (of course), but it also gives us a lot "for free" - it can build packages of various types (pet, deb, rpm, txz, tgz, etc), with lots of options and customisations available, etc.

In fact, looking at the help output, going through the code, and given that `src2pkg` can build from build scripts, but also straight from URL or archive file, it looks like `src2pkg` would be a great option to use as the 'core' of any "source to package" system... 

If we did use `src2pkg` as the basis for any petbuild replacement, we may of course have to update some code, add some new helpers to it, etc ... Which would mean we need **amigo** on board, or at least for amigo to give us permission to "fork" it or something..

**Comment by sc0ttj** [comment]
So, to conclude, my preferred options are these, in order of most preferred to least:

## 1. use `src2pkg` as the 'core' of a new system

Benefits:

- it's basically "first in class" for what it does
- we can leverage its SlackBuild scripts to "native" (src2pkg compatible) build scripts functionality
- it doesn't even need build scripts - just a URL to archive file, or a local archive file
- but it can even generate build scripts for us (which we can fix up if needed)
- it can build .pet, .deb, txz, etc ... can extend to build more (sfs?)
- it has excellent handling of pre/post install script stuff (which we could port into Pkg)
- it can install packages (we won't need this bit).. 

## 2.  Integrate features and fixes from petbuild into buildpet, use buildpet

Benefits:

- buildpet is already setup to receive custom build options from Pkg, via the `--configure` and `--cflags` params (see example [here](https://github.com/puppylinux-woof-CE/Pkg/issues/13))
- can source the build scripts properly (unlike petbuild, which _runs_ them) 
- build scripts seem simpler and more 'generic' or portable than petbuild
- it seems easier to port other build scripts (slackbuild etc) to buildpet than petbuild

## 3. Improve petbuild, use that

Benefits:

- I don't know (cos I don't know about it)

@01micko , @wdlkmpx  .... thoughts on the above?

**Comment by sc0ttj** [comment]
Any ideas guys?
